# Generated by Django 3.1.2 on 2020-11-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.IntegerField(max_length=3)),
                ('sexo', models.CharField(max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residencial', models.CharField(max_length=20)),
                ('comercial', models.CharField(max_length=20)),
            ],
        ),
    ]
